Add oauth http proxy for external server & Extract email from azure claim
flyteorg/flyteadmin pull request #553
Opened 2023-04-27 08:27 UTC by ByronHsu

# TL;DR

1. Add oauth http proxy for external server
2. Extract email from azure claim

## Type
 - [x] Bug Fix
 - [x] Feature
 - [ ] Plugin

## Are all requirements met?

 - [x] Code completed
 - [ ] Smoke tested
 - [x] Unit tests added
 - [ ] Code documentation added
 - [ ] Any pending items have an associated Issue

## Tracking Issue
_Remove the '*fixes*' keyword if there will be multiple PRs to fix the linked issue_

fixes https://github.com/flyteorg/flyte/issues/<number>
https://github.com/flyteorg/flyte/issues/3620

## Follow-up issue
_NA_
OR
_https://github.com/flyteorg/flyte/issues/<number>_

2023-05-10 17:36 UTC, wild-endeavor submitted a review, later dismissed

2023-05-11 17:50 UTC, wild-endeavor reviewed
i think this needs a `make generate` or a `go generate ./...` or something

2023-05-12 18:17 UTC, wild-endeavor approved these changes

2023-05-12 23:02 UTC, EngHabu requested changes

2023-05-12 23:02 UTC, EngHabu commented on auth/token.go
> +	logger.Debugf(ctx, "Access Token = %v", tokenStr)
Let's not write sensitive data to logs

2023-05-12 23:02 UTC, EngHabu commented on auth/token.go
> +	logger.Debugf(ctx, "ID Token = %v", tokenStr)
ditto

2023-05-16 05:34 UTC, wild-endeavor approved these changes

2023-05-16 16:40 UTC, EngHabu approved these changes

2023-05-16 16:48 UTC, merged